# Fonts
font_family Source Code Pro
italic_font auto
bold_italic_font auto
font_size 14.0
cursor_blink_interval -1
mouse_hide_wait 2.0
open_url_with default
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh
detect_urls yes
copy_on_select yes
startup_session launch.conf
confirm_os_window_close 0
# Only use this on gnome for window decorations, not a great idea
# linux_display_server x11 

# Themes
background #2E3440
foreground #CACFD2
cursor #CACFD2
selection_foreground #CACFD2
selection_background #6a7984
color0 #151515
color1 #bf616a
color2 #A3B58C
color3 #ebc17a
color4 #81a1c1
color5 #bf616a
color6 #c9dfff
color7 #d9d9d9
color8 #636363
color9 #bf616a
color10 #A3B58C
color11 #ebc17a
color12 #81a1c1
color13 #bf616a
color14 #acbbd0
color15 #f7f7f7

term xterm-256color
background_opacity 0.9
background_blur 2



