format = """
[░▓](#D8DEE9)\
[ ✙ ](bg:#D8DEE9 fg:#2E3440)\
[](bg:#81A1C1 fg:#D8DEE9)\
$directory\
[](fg:#81A1C1 bg:#3B4252)\
$git_branch\
$git_status\
[](fg:#3B4252 bg:#4C566A)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#4C566A bg:#2E3440)\
$time\
[ ](fg:#2E3440)\
\n$character"""

[directory]
style = "fg:#E5E9F0 bg:#81A1C1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#3B4252"
format = '[[ $symbol $branch ](fg:#81A1C1 bg:#3B4252)]($style)'

[git_status]
style = "bg:#3B4252"
format = '[[($all_status$ahead_behind )](fg:#81A1C1 bg:#3B4252)]($style)'

[nodejs]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[rust]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[golang]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[php]
symbol = ""
style = "bg:#4C566A"
format = '[[ $symbol ($version) ](fg:#81A1C1 bg:#4C566A)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2E3440"
format = '[[  $time ](fg:#D8DEE9 bg:#2E3440)]($style)'
